# file: postgresql/tasks/install.yml

- name: PostgreSQL | Make sure the dependencies are installed
  pkgng:
    name: "{{item}}"
    state: present
  with_items:
  - "py27-psycopg2"
  - "py27-curl"
  - "curl"
  - "sudo"

- name: PostgreSQL | Install PostgreSQL
  pkgng:
    name: "{{item}}"
    state: present
  with_items:
    - "postgresql{{postgresql_version}}-server"
    - "postgresql{{postgresql_version}}-client"
    - "postgresql{{postgresql_version}}-contrib"
